apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: sucvirv2-servicio-comp-cargas-familiares
    app.kubernetes.io/component: sucvirv2-servicio-comp-cargas-familiares
    app.kubernetes.io/instance: sucvirv2-servicio-comp-cargas-familiares
  name: sucvirv2-servicio-comp-cargas-familiares
spec:
  lookupPolicy:
    local: false
